drop schema public cascade;

drop table if exists uzytkownik;
create table uzytkownik (
    id bigint generated by default as identity primary key,
    login varchar(50) not null,
    email varchar(100) not null
);

drop table if exists follower;
create table follower (
    id bigint generated by default as identity primary key,
    uzytkownik_id bigint not null,
    follower_id bigint not null
);

drop table if exists wpis;
create table wpis (
    id bigint generated by default as identity primary key,
    uzytkownik_id bigint not null,
    tresc varchar(500) not null
);
